### ISSUE TITLE
The patreon button isnt centered

### ISSUE THREAD

**Issue by Niceygy** [UFO-Studios/TheAlienDoctor.com#31]
As above

**Comment by TheAlienDoctor** [comment]
It *was* working. Nothing was changed one the website and one day it stopped working again.
Even looking at older versions its just broken.

Putting the embed with only the necessary html code into a new file completely unrelated from the site still showed it not working. Its also not just a centre-ing issue. The shade of orange looks wrong (to me) and its meant to have rounded corners with a different font.

**Comment by MDxWARRIORxOP** [comment]
oh
