### ISSUE TITLE
YouTube embed code isn't reactive

### ISSUE THREAD

**Issue by TheAlienDoctor** [UFO-Studios/TheAlienDoctor.com#7]
The code that embeds YouTube videos isnt reactive, meaning its not adjusting when resized or being used on mobile.
Preferably a fix for this would be with CSS, as we already have rules for a div in the style.css file for this sort of thing from the original template that don't seem to work.

**Comment by MDxWARRIORxOP** [comment]
Maybe this'll help: https://youtu.be/9YffrCViTVk

**Comment by Thisisniceygy** [comment]
I'll check it out later, thx @MDxWARRIORxOP

**Comment by MDxWARRIORxOP** [comment]
np @Thisisniceygy

**Comment by NiceygyLive** [comment]
Fixed #c9d64af
